apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: dvwa-ingress
  namespace: dvwa
spec:
  ingressClassName: nginx
  rules:
  - host: dvwa.lim.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: dvwa-service
            port:
              number: 80
