apiVersion: v1
kind: Service
metadata:
  name: dvwa-service
  namespace: dvwa
  labels:
    app: dvwa
spec:
  type: NodePort
  selector:
    app: dvwa
  ports:
  - port: 80          # Service 监听的端口
    targetPort: 80    # Pod 中容器暴露的端口
    nodePort: 30080
    protocol: TCP
